# Node docker image
image: node:8.10.0

cache:
  paths:
    - node_module/

stages:
  - install
  - deploy

#Job 1 Install
Install:
  stage: install
  script:
    - npm install

#Job 2 DEPLOY:
Production:
  image: ruby:latest
  only:
    - main
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
